// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteClient(arg1) {
  return window['go']['main']['App']['DeleteClient'](arg1);
}

export function DeleteMembership(arg1) {
  return window['go']['main']['App']['DeleteMembership'](arg1);
}

export function DeleteProduct(arg1) {
  return window['go']['main']['App']['DeleteProduct'](arg1);
}

export function DeleteSale(arg1) {
  return window['go']['main']['App']['DeleteSale'](arg1);
}

export function DeleteSubscription(arg1) {
  return window['go']['main']['App']['DeleteSubscription'](arg1);
}

export function GetActivities() {
  return window['go']['main']['App']['GetActivities']();
}

export function GetAllClients() {
  return window['go']['main']['App']['GetAllClients']();
}

export function GetAllMemberships() {
  return window['go']['main']['App']['GetAllMemberships']();
}

export function GetAllProducts() {
  return window['go']['main']['App']['GetAllProducts']();
}

export function GetAllSales() {
  return window['go']['main']['App']['GetAllSales']();
}

export function GetAllSubscriptions() {
  return window['go']['main']['App']['GetAllSubscriptions']();
}

export function GetClientByID(arg1) {
  return window['go']['main']['App']['GetClientByID'](arg1);
}

export function GetDashboard() {
  return window['go']['main']['App']['GetDashboard']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SaveClient(arg1) {
  return window['go']['main']['App']['SaveClient'](arg1);
}

export function SaveMembership(arg1) {
  return window['go']['main']['App']['SaveMembership'](arg1);
}

export function SaveProduct(arg1) {
  return window['go']['main']['App']['SaveProduct'](arg1);
}

export function SaveSale(arg1) {
  return window['go']['main']['App']['SaveSale'](arg1);
}

export function SaveSubscription(arg1) {
  return window['go']['main']['App']['SaveSubscription'](arg1);
}

export function UpdateClient(arg1) {
  return window['go']['main']['App']['UpdateClient'](arg1);
}

export function UpdateMembership(arg1) {
  return window['go']['main']['App']['UpdateMembership'](arg1);
}

export function UpdateProduct(arg1) {
  return window['go']['main']['App']['UpdateProduct'](arg1);
}

export function UpdateSale(arg1) {
  return window['go']['main']['App']['UpdateSale'](arg1);
}

export function UpdateSubscription(arg1) {
  return window['go']['main']['App']['UpdateSubscription'](arg1);
}
