// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {delete_client} from '../models';
import {delete_membership} from '../models';
import {delete_product} from '../models';
import {delete_subscription} from '../models';
import {get_clients} from '../models';
import {get_memberships} from '../models';
import {get_products} from '../models';
import {get_subscriptions} from '../models';
import {get_client_by_id} from '../models';
import {save_client} from '../models';
import {save_membership} from '../models';
import {save_product} from '../models';
import {save_subscription} from '../models';
import {update_client} from '../models';
import {update_membership} from '../models';
import {update_product} from '../models';
import {update_subscription} from '../models';

export function DeleteClient(arg1:delete_client.DeleteClientRequest):Promise<void>;

export function DeleteMembership(arg1:delete_membership.DeleteMembershipRequest):Promise<void>;

export function DeleteProduct(arg1:delete_product.DeleteProductRequest):Promise<void>;

export function DeleteSubscription(arg1:delete_subscription.DeleteSubscriptionRequest):Promise<void>;

export function GetAllClients():Promise<Array<get_clients.ClientResponse>>;

export function GetAllMemberships():Promise<Array<get_memberships.MembershipResponse>>;

export function GetAllProducts():Promise<Array<get_products.ProductResponse>>;

export function GetAllSubscriptions():Promise<Array<get_subscriptions.SubscriptionResponse>>;

export function GetClientByID(arg1:get_client_by_id.GetClientByIDQuery):Promise<get_client_by_id.ClientResponse>;

export function Greet(arg1:string):Promise<string>;

export function SaveClient(arg1:save_client.SaveClientRequest):Promise<void>;

export function SaveMembership(arg1:save_membership.SaveMembershipRequest):Promise<void>;

export function SaveProduct(arg1:save_product.SaveProductRequest):Promise<void>;

export function SaveSubscription(arg1:save_subscription.SaveSubscriptionRequest):Promise<void>;

export function UpdateClient(arg1:update_client.UpdateClientRequest):Promise<void>;

export function UpdateMembership(arg1:update_membership.UpdateMembershipRequest):Promise<void>;

export function UpdateProduct(arg1:update_product.UpdateProductRequest):Promise<void>;

export function UpdateSubscription(arg1:update_subscription.UpdateSubscriptionRequest):Promise<void>;
