name: Release (Linux)

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Install frontend deps
        run: |
          cd frontend
          npm install

      - name: Install system dependencies (GTK, WebKit, etc.)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libwebkit2gtk-4.1-dev \
            libayatana-appindicator3-dev \
            libx11-dev \
            libnss3 \
            libasound2-dev

      - name: Build Wails app (Linux)
        run: wails build -tags webkit2_41 -platform linux/amd64

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wails-linux
          path: build/bin/*

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/bin/*
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
