name: Release (Windows)

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Wails
        run: go install github.com/wailsapp/wails/v3/cmd/wails@latest

      - name: Install frontend deps
        run: |
          cd frontend
          npm install

      - name: Install Visual Studio Build Tools (C/C++)
        uses: microsoft/setup-msbuild@v1

      - name: Set CGO_ENABLED
        run: setx CGO_ENABLED 1

      - name: Build Wails app (Windows)
        run: wails build -platform windows/amd64

      - name: Rename binary with version
        run: |
          $exeName = "POSApp.exe"
          $newName = "POS_v${{ github.ref_name }}.exe"
          Rename-Item "build\bin\$exeName" $newName

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wails-windows
          path: build/bin/*

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/bin/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
